### PR TITLE
delete bottom in swiper-container

### PR DESCRIPTION
**Pull request by BehnooshShiva**
swiper slips on the over element
image

### CODE REVIEW

**Comment by Lausselloic** [comment]
image
Yes something need to be fixed, but that fix create another problem, play/pause button changing state when mouseout becaus it's covered by the carousel layout. 
Maybe the fix could be to add padding top? I hadn't try

**Comment by BehnooshShiva** [comment]
@Lausselloic 
This is not a bug. it's programmed like that to be able to click (right and left) on the element in the slide
` @HostListener('mouseenter') public onMouseEnter() {
      if (this.swiper) {
        this.swiper.autoplay.stop();
      }
      this.pause = !this.pause;
    }

    @HostListener('mouseleave') public onMouseLeave() {
      if (this.swiper) {
        this.swiper.autoplay.start();
      }
      this.pause = !this.pause;
    }

    @HostListener('focus') public onFocusIn() {
      if (this.swiper) {
        this.swiper.autoplay.start();
      }
      this.pause = !this.pause;
    }

    @HostListener('blur') public onFocusOut() {
      if (this.swiper) {
        this.swiper.autoplay.start();
      }
      this.pause = !this.pause;
    }`

**Comment by BehnooshShiva** [comment]
This is not a bug. it's programmed like that to be able to click (right and left) on the element in the slide
`
@HostListener('mouseenter') public onMouseEnter() {
      if (this.swiper) {
        this.swiper.autoplay.stop();
      }
      this.pause = !this.pause;
    }

    @HostListener('mouseleave') public onMouseLeave() {
      if (this.swiper) {
        this.swiper.autoplay.start();
      }
      this.pause = !this.pause;
    }

    @HostListener('focus') public onFocusIn() {
      if (this.swiper) {
        this.swiper.autoplay.start();
      }
      this.pause = !this.pause;
    }

    @HostListener('blur') public onFocusOut() {
      if (this.swiper) {
        this.swiper.autoplay.start();
      }
      this.pause = !this.pause;
    }
`

**Comment by Lausselloic** [comment]
Yes you're right, it's already buggy in production.
There's something to fix on that, if you go to clic on pause, you don't want to restart on mouseout, so maybe check if user have use the play/pause button to force the pause status then don't restart autoplay on mouseout

**Comment by ffoodd** [comment]
@Lausselloic Why do we have mouse event listeners related to autplay carousel at all?

My two cents: since there's a play/pause button, we should only rely on it being pressed or not, shouldn't we?

**Pull request merged**
